### ISSUE TITLE
All flying mobs have borked spawns

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/Mobzy#56]
Tested both on server and locally. Seemingly it just does not spawn any of them even if mobcaps are set to 100.

Tested with hammerbeaks in Layer 1 as:
mobzy:flying / mobzy:hostile
creatureType: MISC / MONSTER / CREATURE
and caps at 100 for all types, still nothing like before.
Not sure what has changed other than projectile stuff, everything is like it was before kagis were added.

**Comment by 0ffz** [comment]
Suspected issues:
- ~~MISC cap is used up by other entities~~ (turns out I was smart enough to only check the cap for custom mobs, so this can't be the issue)
- Calculation for the mob cap is done improperly somewhere

Spawn system will go through a small rewrite to be far more modular once I'm done with the Geary rewrite. Hopefully this issue resolves itself then.

**Comment by Boy0000** [comment]
literally cuz min-y/max-y wasnt added on plugin rewrite
