### ISSUE TITLE
Mobs dont visibly burn

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/Mobzy#88]
### Expected behavior

Mobs hit by Flame or Fire Aspect or lava should visibly burn

### Observed/Actual behavior

They dont cuz armorstands dont burn

### Steps/models to reproduce

hit mob
no burn

**Comment by 0ffz** [comment]
This is impossible to do with one armor stand packet as marker armor stands don't burn. The system needs to be made to send another burning armor stand packet when it is on fire and that is quite complicated.

**Comment by Kasaichan** [comment]
Proposing two solutions, though I'm unsure how effective these would be:

Option 1: The issue's title and expected behavior is looking for the **visual** effect of flames, which can be reproduced by displaying a [custom particle](https://snowstorm.app/) while the mob is detected to be on fire. [Particles seem about as easy to implement as sound files](https://docs.microsoft.com/en-us/minecraft/creator/documents/particleeffects#commands). Doesn't necessarily have to be applied to new textures, modifying pre-existing ones work too. Only difficulty I'm running into is applying the particle to a non-stationary entity.
Here's the start of option 1's solution: [particle-setup.zip](https://github.com/MineInAbyss/Mobzy/files/8704763/particle-setup.zip)

Option 2: If the flame doesn't work with armor stands, then what prevents burning a different entity to indicate fire? An invisible slime would generally fit all sizes of flame, but at the cost of an additional entity and having to write code to detect a creature's size to proportion it to the slimes. This option is also under the assumption that the entity is attempting to detect if it's on fire.

**Comment by 0ffz** [comment]
Slime should actually be doable, I might forward that as a feature request to the ME guy if they have tried to get fire working on their end but havent been able to. Maybe get some insight from them.

**Comment by Boy0000** [comment]
I recall Ticxo mentioning adding slimes for hitbox related reasons so I suppose this would be an extra benefit to that

**Comment by Boy0000** [comment]
planned meg feature
